-- 유저
INSERT INTO AUTHORITY (CREATED_AT, UPDATED_AT, AUTHORITY_NAME)
values (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ROLE_USER');

INSERT INTO AUTHORITY (CREATED_AT, UPDATED_AT, AUTHORITY_NAME)
values (CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ROLE_ADMIN');
