-- 유저
INSERT INTO AUTHORITY (ID, CREATED_AT, UPDATED_AT, AUTHORITY_NAME)
VALUES (1, NOW(), NOW(), 'ROLE_USER');

INSERT INTO AUTHORITY (ID, CREATED_AT, UPDATED_AT, AUTHORITY_NAME)
VALUES (2, NOW(), NOW(), 'ROLE_ADMIN');

INSERT INTO USER (ID, CREATED_AT, UPDATED_AT, EMAIL, FIELD, GITHUB_ID, JOIN_GISU, NAME, PASSWORD, STATUS)
VALUES (1, NOW(), NOW(), 'j2kb2@j2kb.com', 'NONE', 'jikimee64@gmail.com',
        '2기', '김우철', '$2a$10$jne/g4mnJ74uZSjsZr5.fOHPUJkeBr5JMPw.mvMvFjo0n9KapMHoe', 'ACTIVE');

INSERT INTO USER_AUTHORITY(ID, CREATED_AT, UPDATED_AT, AUTHORITY_ID, USER_ID)
VALUES (1, NOW(), NOW(), 1, 1);

INSERT INTO GISU_CATEGORY(ID, CREATED_AT, UPDATED_AT, GISU)
VALUES (1, NOW(), NOW(), '2기');

INSERT INTO TEAM(ID, CREATED_AT, UPDATED_AT, TEAM_NAME, GISU_CATEGORY_ID)
VALUES(1, NOW(), NOW(), 'codev-21', 1);

INSERT INTO USER_TEAM(ID, CREATED_AT, UPDATED_AT, LEADER, TEAM_ID, USER_ID)
VALUES(1, NOW(), NOW(), TRUE, 1, 1);

INSERT INTO BOARD(ID, CREATED_AT, UPDATED_AT, CONTENT, IMAGE, SUMMARY, TITLE, WRITER, GISU_CATEGORY_ID, TEAM_ID, USER_ID)
VALUES(1, NOW(), NOW(), '프로젝트 내용입니다.',
       'https://www.all-con.co.kr/data/poster/2103/462627.jpg?v=1615473570', '요약 입니다', '제목 입니다.',
       'jikimee64@gmail.com', 1, 1, 1);
